// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: ItemMaster.proto

package itemmasterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemMasterProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId     int32  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemNumber string `protobuf:"bytes,2,opt,name=item_number,json=itemNumber,proto3" json:"item_number,omitempty"`
	ItemName   string `protobuf:"bytes,3,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
}

func (x *ItemMasterProto) Reset() {
	*x = ItemMasterProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ItemMaster_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemMasterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemMasterProto) ProtoMessage() {}

func (x *ItemMasterProto) ProtoReflect() protoreflect.Message {
	mi := &file_ItemMaster_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemMasterProto.ProtoReflect.Descriptor instead.
func (*ItemMasterProto) Descriptor() ([]byte, []int) {
	return file_ItemMaster_proto_rawDescGZIP(), []int{0}
}

func (x *ItemMasterProto) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemMasterProto) GetItemNumber() string {
	if x != nil {
		return x.ItemNumber
	}
	return ""
}

func (x *ItemMasterProto) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

type CreateItemMasterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemMaster *ItemMasterProto `protobuf:"bytes,1,opt,name=item_master,json=itemMaster,proto3" json:"item_master,omitempty"`
}

func (x *CreateItemMasterRequest) Reset() {
	*x = CreateItemMasterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ItemMaster_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateItemMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemMasterRequest) ProtoMessage() {}

func (x *CreateItemMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ItemMaster_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemMasterRequest.ProtoReflect.Descriptor instead.
func (*CreateItemMasterRequest) Descriptor() ([]byte, []int) {
	return file_ItemMaster_proto_rawDescGZIP(), []int{1}
}

func (x *CreateItemMasterRequest) GetItemMaster() *ItemMasterProto {
	if x != nil {
		return x.ItemMaster
	}
	return nil
}

type CreateItemMasterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemMaster *ItemMasterProto `protobuf:"bytes,1,opt,name=item_master,json=itemMaster,proto3" json:"item_master,omitempty"`
}

func (x *CreateItemMasterResponse) Reset() {
	*x = CreateItemMasterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ItemMaster_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateItemMasterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemMasterResponse) ProtoMessage() {}

func (x *CreateItemMasterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ItemMaster_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemMasterResponse.ProtoReflect.Descriptor instead.
func (*CreateItemMasterResponse) Descriptor() ([]byte, []int) {
	return file_ItemMaster_proto_rawDescGZIP(), []int{2}
}

func (x *CreateItemMasterResponse) GetItemMaster() *ItemMasterProto {
	if x != nil {
		return x.ItemMaster
	}
	return nil
}

type GetAllItemMasterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllItemMasterRequest) Reset() {
	*x = GetAllItemMasterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ItemMaster_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllItemMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemMasterRequest) ProtoMessage() {}

func (x *GetAllItemMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ItemMaster_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemMasterRequest.ProtoReflect.Descriptor instead.
func (*GetAllItemMasterRequest) Descriptor() ([]byte, []int) {
	return file_ItemMaster_proto_rawDescGZIP(), []int{3}
}

type GetAllItemMasterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemMasterList []*ItemMasterProto `protobuf:"bytes,1,rep,name=item_master_list,json=itemMasterList,proto3" json:"item_master_list,omitempty"`
}

func (x *GetAllItemMasterResponse) Reset() {
	*x = GetAllItemMasterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ItemMaster_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllItemMasterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemMasterResponse) ProtoMessage() {}

func (x *GetAllItemMasterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ItemMaster_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemMasterResponse.ProtoReflect.Descriptor instead.
func (*GetAllItemMasterResponse) Descriptor() ([]byte, []int) {
	return file_ItemMaster_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllItemMasterResponse) GetItemMasterList() []*ItemMasterProto {
	if x != nil {
		return x.ItemMasterList
	}
	return nil
}

var File_ItemMaster_proto protoreflect.FileDescriptor

var file_ItemMaster_proto_rawDesc = []byte{
	0x0a, 0x10, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x68,
	0x0a, 0x0f, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x74,
	0x65, 0x6d, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x69,
	0x74, 0x65, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x57, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x6d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x6d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x22, 0x58, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x4d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a,
	0x0b, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x0a, 0x69, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x22, 0x19, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x61, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x49, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x45, 0x0a, 0x10, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x69,
	0x74, 0x65, 0x6d, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0e, 0x69, 0x74, 0x65, 0x6d, 0x4d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x32, 0xd1, 0x01, 0x0a, 0x11, 0x49, 0x74,
	0x65, 0x6d, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5d, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x6d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x23, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x6d, 0x61,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x4d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a,
	0x0f, 0x2e, 0x2f, 0x3b, 0x69, 0x74, 0x65, 0x6d, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ItemMaster_proto_rawDescOnce sync.Once
	file_ItemMaster_proto_rawDescData = file_ItemMaster_proto_rawDesc
)

func file_ItemMaster_proto_rawDescGZIP() []byte {
	file_ItemMaster_proto_rawDescOnce.Do(func() {
		file_ItemMaster_proto_rawDescData = protoimpl.X.CompressGZIP(file_ItemMaster_proto_rawDescData)
	})
	return file_ItemMaster_proto_rawDescData
}

var file_ItemMaster_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ItemMaster_proto_goTypes = []interface{}{
	(*ItemMasterProto)(nil),          // 0: itemmaster.ItemMasterProto
	(*CreateItemMasterRequest)(nil),  // 1: itemmaster.CreateItemMasterRequest
	(*CreateItemMasterResponse)(nil), // 2: itemmaster.CreateItemMasterResponse
	(*GetAllItemMasterRequest)(nil),  // 3: itemmaster.GetAllItemMasterRequest
	(*GetAllItemMasterResponse)(nil), // 4: itemmaster.GetAllItemMasterResponse
}
var file_ItemMaster_proto_depIdxs = []int32{
	0, // 0: itemmaster.CreateItemMasterRequest.item_master:type_name -> itemmaster.ItemMasterProto
	0, // 1: itemmaster.CreateItemMasterResponse.item_master:type_name -> itemmaster.ItemMasterProto
	0, // 2: itemmaster.GetAllItemMasterResponse.item_master_list:type_name -> itemmaster.ItemMasterProto
	1, // 3: itemmaster.ItemMasterService.CreateItemMaster:input_type -> itemmaster.CreateItemMasterRequest
	3, // 4: itemmaster.ItemMasterService.GetAllItemMaster:input_type -> itemmaster.GetAllItemMasterRequest
	2, // 5: itemmaster.ItemMasterService.CreateItemMaster:output_type -> itemmaster.CreateItemMasterResponse
	4, // 6: itemmaster.ItemMasterService.GetAllItemMaster:output_type -> itemmaster.GetAllItemMasterResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ItemMaster_proto_init() }
func file_ItemMaster_proto_init() {
	if File_ItemMaster_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ItemMaster_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemMasterProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ItemMaster_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateItemMasterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ItemMaster_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateItemMasterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ItemMaster_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllItemMasterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ItemMaster_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllItemMasterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ItemMaster_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ItemMaster_proto_goTypes,
		DependencyIndexes: file_ItemMaster_proto_depIdxs,
		MessageInfos:      file_ItemMaster_proto_msgTypes,
	}.Build()
	File_ItemMaster_proto = out.File
	file_ItemMaster_proto_rawDesc = nil
	file_ItemMaster_proto_goTypes = nil
	file_ItemMaster_proto_depIdxs = nil
}
