// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MfsUsersColumns holds the columns for the "mfs_users" table.
	MfsUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "username", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "address", Type: field.TypeString, Nullable: true},
	}
	// MfsUsersTable holds the schema information for the "mfs_users" table.
	MfsUsersTable = &schema.Table{
		Name:       "mfs_users",
		Columns:    MfsUsersColumns,
		PrimaryKey: []*schema.Column{MfsUsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MfsUsersTable,
	}
)

func init() {
}
