// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fukunokaze/mfs_backend/MFSRepository/ent/mfsuser"
	"github.com/fukunokaze/mfs_backend/MFSRepository/ent/predicate"
)

// MFSUserQuery is the builder for querying MFSUser entities.
type MFSUserQuery struct {
	config
	ctx        *QueryContext
	order      []mfsuser.OrderOption
	inters     []Interceptor
	predicates []predicate.MFSUser
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MFSUserQuery builder.
func (muq *MFSUserQuery) Where(ps ...predicate.MFSUser) *MFSUserQuery {
	muq.predicates = append(muq.predicates, ps...)
	return muq
}

// Limit the number of records to be returned by this query.
func (muq *MFSUserQuery) Limit(limit int) *MFSUserQuery {
	muq.ctx.Limit = &limit
	return muq
}

// Offset to start from.
func (muq *MFSUserQuery) Offset(offset int) *MFSUserQuery {
	muq.ctx.Offset = &offset
	return muq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (muq *MFSUserQuery) Unique(unique bool) *MFSUserQuery {
	muq.ctx.Unique = &unique
	return muq
}

// Order specifies how the records should be ordered.
func (muq *MFSUserQuery) Order(o ...mfsuser.OrderOption) *MFSUserQuery {
	muq.order = append(muq.order, o...)
	return muq
}

// First returns the first MFSUser entity from the query.
// Returns a *NotFoundError when no MFSUser was found.
func (muq *MFSUserQuery) First(ctx context.Context) (*MFSUser, error) {
	nodes, err := muq.Limit(1).All(setContextOp(ctx, muq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mfsuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (muq *MFSUserQuery) FirstX(ctx context.Context) *MFSUser {
	node, err := muq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MFSUser ID from the query.
// Returns a *NotFoundError when no MFSUser ID was found.
func (muq *MFSUserQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = muq.Limit(1).IDs(setContextOp(ctx, muq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mfsuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (muq *MFSUserQuery) FirstIDX(ctx context.Context) int {
	id, err := muq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MFSUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MFSUser entity is found.
// Returns a *NotFoundError when no MFSUser entities are found.
func (muq *MFSUserQuery) Only(ctx context.Context) (*MFSUser, error) {
	nodes, err := muq.Limit(2).All(setContextOp(ctx, muq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mfsuser.Label}
	default:
		return nil, &NotSingularError{mfsuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (muq *MFSUserQuery) OnlyX(ctx context.Context) *MFSUser {
	node, err := muq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MFSUser ID in the query.
// Returns a *NotSingularError when more than one MFSUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (muq *MFSUserQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = muq.Limit(2).IDs(setContextOp(ctx, muq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mfsuser.Label}
	default:
		err = &NotSingularError{mfsuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (muq *MFSUserQuery) OnlyIDX(ctx context.Context) int {
	id, err := muq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MFSUsers.
func (muq *MFSUserQuery) All(ctx context.Context) ([]*MFSUser, error) {
	ctx = setContextOp(ctx, muq.ctx, "All")
	if err := muq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MFSUser, *MFSUserQuery]()
	return withInterceptors[[]*MFSUser](ctx, muq, qr, muq.inters)
}

// AllX is like All, but panics if an error occurs.
func (muq *MFSUserQuery) AllX(ctx context.Context) []*MFSUser {
	nodes, err := muq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MFSUser IDs.
func (muq *MFSUserQuery) IDs(ctx context.Context) (ids []int, err error) {
	if muq.ctx.Unique == nil && muq.path != nil {
		muq.Unique(true)
	}
	ctx = setContextOp(ctx, muq.ctx, "IDs")
	if err = muq.Select(mfsuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (muq *MFSUserQuery) IDsX(ctx context.Context) []int {
	ids, err := muq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (muq *MFSUserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, muq.ctx, "Count")
	if err := muq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, muq, querierCount[*MFSUserQuery](), muq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (muq *MFSUserQuery) CountX(ctx context.Context) int {
	count, err := muq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (muq *MFSUserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, muq.ctx, "Exist")
	switch _, err := muq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (muq *MFSUserQuery) ExistX(ctx context.Context) bool {
	exist, err := muq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MFSUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (muq *MFSUserQuery) Clone() *MFSUserQuery {
	if muq == nil {
		return nil
	}
	return &MFSUserQuery{
		config:     muq.config,
		ctx:        muq.ctx.Clone(),
		order:      append([]mfsuser.OrderOption{}, muq.order...),
		inters:     append([]Interceptor{}, muq.inters...),
		predicates: append([]predicate.MFSUser{}, muq.predicates...),
		// clone intermediate query.
		sql:  muq.sql.Clone(),
		path: muq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserId int `json:"userId,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MFSUser.Query().
//		GroupBy(mfsuser.FieldUserId).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (muq *MFSUserQuery) GroupBy(field string, fields ...string) *MFSUserGroupBy {
	muq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MFSUserGroupBy{build: muq}
	grbuild.flds = &muq.ctx.Fields
	grbuild.label = mfsuser.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserId int `json:"userId,omitempty"`
//	}
//
//	client.MFSUser.Query().
//		Select(mfsuser.FieldUserId).
//		Scan(ctx, &v)
func (muq *MFSUserQuery) Select(fields ...string) *MFSUserSelect {
	muq.ctx.Fields = append(muq.ctx.Fields, fields...)
	sbuild := &MFSUserSelect{MFSUserQuery: muq}
	sbuild.label = mfsuser.Label
	sbuild.flds, sbuild.scan = &muq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MFSUserSelect configured with the given aggregations.
func (muq *MFSUserQuery) Aggregate(fns ...AggregateFunc) *MFSUserSelect {
	return muq.Select().Aggregate(fns...)
}

func (muq *MFSUserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range muq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, muq); err != nil {
				return err
			}
		}
	}
	for _, f := range muq.ctx.Fields {
		if !mfsuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if muq.path != nil {
		prev, err := muq.path(ctx)
		if err != nil {
			return err
		}
		muq.sql = prev
	}
	return nil
}

func (muq *MFSUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MFSUser, error) {
	var (
		nodes = []*MFSUser{}
		_spec = muq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MFSUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MFSUser{config: muq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, muq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (muq *MFSUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := muq.querySpec()
	_spec.Node.Columns = muq.ctx.Fields
	if len(muq.ctx.Fields) > 0 {
		_spec.Unique = muq.ctx.Unique != nil && *muq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, muq.driver, _spec)
}

func (muq *MFSUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(mfsuser.Table, mfsuser.Columns, sqlgraph.NewFieldSpec(mfsuser.FieldID, field.TypeInt))
	_spec.From = muq.sql
	if unique := muq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if muq.path != nil {
		_spec.Unique = true
	}
	if fields := muq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mfsuser.FieldID)
		for i := range fields {
			if fields[i] != mfsuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := muq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := muq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := muq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := muq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (muq *MFSUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(muq.driver.Dialect())
	t1 := builder.Table(mfsuser.Table)
	columns := muq.ctx.Fields
	if len(columns) == 0 {
		columns = mfsuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if muq.sql != nil {
		selector = muq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if muq.ctx.Unique != nil && *muq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range muq.predicates {
		p(selector)
	}
	for _, p := range muq.order {
		p(selector)
	}
	if offset := muq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := muq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MFSUserGroupBy is the group-by builder for MFSUser entities.
type MFSUserGroupBy struct {
	selector
	build *MFSUserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mugb *MFSUserGroupBy) Aggregate(fns ...AggregateFunc) *MFSUserGroupBy {
	mugb.fns = append(mugb.fns, fns...)
	return mugb
}

// Scan applies the selector query and scans the result into the given value.
func (mugb *MFSUserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mugb.build.ctx, "GroupBy")
	if err := mugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MFSUserQuery, *MFSUserGroupBy](ctx, mugb.build, mugb, mugb.build.inters, v)
}

func (mugb *MFSUserGroupBy) sqlScan(ctx context.Context, root *MFSUserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mugb.fns))
	for _, fn := range mugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mugb.flds)+len(mugb.fns))
		for _, f := range *mugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MFSUserSelect is the builder for selecting fields of MFSUser entities.
type MFSUserSelect struct {
	*MFSUserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mus *MFSUserSelect) Aggregate(fns ...AggregateFunc) *MFSUserSelect {
	mus.fns = append(mus.fns, fns...)
	return mus
}

// Scan applies the selector query and scans the result into the given value.
func (mus *MFSUserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mus.ctx, "Select")
	if err := mus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MFSUserQuery, *MFSUserSelect](ctx, mus.MFSUserQuery, mus, mus.inters, v)
}

func (mus *MFSUserSelect) sqlScan(ctx context.Context, root *MFSUserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mus.fns))
	for _, fn := range mus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
