// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/fukunokaze/mfs_backend/MFSRepository/ent/mfsuser"
	"github.com/fukunokaze/mfs_backend/MFSRepository/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeMFSUser = "MFSUser"
)

// MFSUserMutation represents an operation that mutates the MFSUser nodes in the graph.
type MFSUserMutation struct {
	config
	op            Op
	typ           string
	id            *int
	userId        *int
	adduserId     *int
	username      *string
	password      *string
	address       *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*MFSUser, error)
	predicates    []predicate.MFSUser
}

var _ ent.Mutation = (*MFSUserMutation)(nil)

// mfsuserOption allows management of the mutation configuration using functional options.
type mfsuserOption func(*MFSUserMutation)

// newMFSUserMutation creates new mutation for the MFSUser entity.
func newMFSUserMutation(c config, op Op, opts ...mfsuserOption) *MFSUserMutation {
	m := &MFSUserMutation{
		config:        c,
		op:            op,
		typ:           TypeMFSUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withMFSUserID sets the ID field of the mutation.
func withMFSUserID(id int) mfsuserOption {
	return func(m *MFSUserMutation) {
		var (
			err   error
			once  sync.Once
			value *MFSUser
		)
		m.oldValue = func(ctx context.Context) (*MFSUser, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().MFSUser.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMFSUser sets the old MFSUser of the mutation.
func withMFSUser(node *MFSUser) mfsuserOption {
	return func(m *MFSUserMutation) {
		m.oldValue = func(context.Context) (*MFSUser, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m MFSUserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m MFSUserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *MFSUserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *MFSUserMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().MFSUser.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUserId sets the "userId" field.
func (m *MFSUserMutation) SetUserId(i int) {
	m.userId = &i
	m.adduserId = nil
}

// UserId returns the value of the "userId" field in the mutation.
func (m *MFSUserMutation) UserId() (r int, exists bool) {
	v := m.userId
	if v == nil {
		return
	}
	return *v, true
}

// OldUserId returns the old "userId" field's value of the MFSUser entity.
// If the MFSUser object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MFSUserMutation) OldUserId(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserId is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserId requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserId: %w", err)
	}
	return oldValue.UserId, nil
}

// AddUserId adds i to the "userId" field.
func (m *MFSUserMutation) AddUserId(i int) {
	if m.adduserId != nil {
		*m.adduserId += i
	} else {
		m.adduserId = &i
	}
}

// AddedUserId returns the value that was added to the "userId" field in this mutation.
func (m *MFSUserMutation) AddedUserId() (r int, exists bool) {
	v := m.adduserId
	if v == nil {
		return
	}
	return *v, true
}

// ResetUserId resets all changes to the "userId" field.
func (m *MFSUserMutation) ResetUserId() {
	m.userId = nil
	m.adduserId = nil
}

// SetUsername sets the "username" field.
func (m *MFSUserMutation) SetUsername(s string) {
	m.username = &s
}

// Username returns the value of the "username" field in the mutation.
func (m *MFSUserMutation) Username() (r string, exists bool) {
	v := m.username
	if v == nil {
		return
	}
	return *v, true
}

// OldUsername returns the old "username" field's value of the MFSUser entity.
// If the MFSUser object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MFSUserMutation) OldUsername(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsername is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsername requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsername: %w", err)
	}
	return oldValue.Username, nil
}

// ResetUsername resets all changes to the "username" field.
func (m *MFSUserMutation) ResetUsername() {
	m.username = nil
}

// SetPassword sets the "password" field.
func (m *MFSUserMutation) SetPassword(s string) {
	m.password = &s
}

// Password returns the value of the "password" field in the mutation.
func (m *MFSUserMutation) Password() (r string, exists bool) {
	v := m.password
	if v == nil {
		return
	}
	return *v, true
}

// OldPassword returns the old "password" field's value of the MFSUser entity.
// If the MFSUser object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MFSUserMutation) OldPassword(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPassword is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPassword requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPassword: %w", err)
	}
	return oldValue.Password, nil
}

// ResetPassword resets all changes to the "password" field.
func (m *MFSUserMutation) ResetPassword() {
	m.password = nil
}

// SetAddress sets the "address" field.
func (m *MFSUserMutation) SetAddress(s string) {
	m.address = &s
}

// Address returns the value of the "address" field in the mutation.
func (m *MFSUserMutation) Address() (r string, exists bool) {
	v := m.address
	if v == nil {
		return
	}
	return *v, true
}

// OldAddress returns the old "address" field's value of the MFSUser entity.
// If the MFSUser object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *MFSUserMutation) OldAddress(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAddress is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAddress requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAddress: %w", err)
	}
	return oldValue.Address, nil
}

// ClearAddress clears the value of the "address" field.
func (m *MFSUserMutation) ClearAddress() {
	m.address = nil
	m.clearedFields[mfsuser.FieldAddress] = struct{}{}
}

// AddressCleared returns if the "address" field was cleared in this mutation.
func (m *MFSUserMutation) AddressCleared() bool {
	_, ok := m.clearedFields[mfsuser.FieldAddress]
	return ok
}

// ResetAddress resets all changes to the "address" field.
func (m *MFSUserMutation) ResetAddress() {
	m.address = nil
	delete(m.clearedFields, mfsuser.FieldAddress)
}

// Where appends a list predicates to the MFSUserMutation builder.
func (m *MFSUserMutation) Where(ps ...predicate.MFSUser) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the MFSUserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *MFSUserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.MFSUser, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *MFSUserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *MFSUserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (MFSUser).
func (m *MFSUserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *MFSUserMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.userId != nil {
		fields = append(fields, mfsuser.FieldUserId)
	}
	if m.username != nil {
		fields = append(fields, mfsuser.FieldUsername)
	}
	if m.password != nil {
		fields = append(fields, mfsuser.FieldPassword)
	}
	if m.address != nil {
		fields = append(fields, mfsuser.FieldAddress)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *MFSUserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case mfsuser.FieldUserId:
		return m.UserId()
	case mfsuser.FieldUsername:
		return m.Username()
	case mfsuser.FieldPassword:
		return m.Password()
	case mfsuser.FieldAddress:
		return m.Address()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *MFSUserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case mfsuser.FieldUserId:
		return m.OldUserId(ctx)
	case mfsuser.FieldUsername:
		return m.OldUsername(ctx)
	case mfsuser.FieldPassword:
		return m.OldPassword(ctx)
	case mfsuser.FieldAddress:
		return m.OldAddress(ctx)
	}
	return nil, fmt.Errorf("unknown MFSUser field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MFSUserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case mfsuser.FieldUserId:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserId(v)
		return nil
	case mfsuser.FieldUsername:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsername(v)
		return nil
	case mfsuser.FieldPassword:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPassword(v)
		return nil
	case mfsuser.FieldAddress:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAddress(v)
		return nil
	}
	return fmt.Errorf("unknown MFSUser field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *MFSUserMutation) AddedFields() []string {
	var fields []string
	if m.adduserId != nil {
		fields = append(fields, mfsuser.FieldUserId)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *MFSUserMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case mfsuser.FieldUserId:
		return m.AddedUserId()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *MFSUserMutation) AddField(name string, value ent.Value) error {
	switch name {
	case mfsuser.FieldUserId:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUserId(v)
		return nil
	}
	return fmt.Errorf("unknown MFSUser numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *MFSUserMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(mfsuser.FieldAddress) {
		fields = append(fields, mfsuser.FieldAddress)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *MFSUserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *MFSUserMutation) ClearField(name string) error {
	switch name {
	case mfsuser.FieldAddress:
		m.ClearAddress()
		return nil
	}
	return fmt.Errorf("unknown MFSUser nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *MFSUserMutation) ResetField(name string) error {
	switch name {
	case mfsuser.FieldUserId:
		m.ResetUserId()
		return nil
	case mfsuser.FieldUsername:
		m.ResetUsername()
		return nil
	case mfsuser.FieldPassword:
		m.ResetPassword()
		return nil
	case mfsuser.FieldAddress:
		m.ResetAddress()
		return nil
	}
	return fmt.Errorf("unknown MFSUser field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *MFSUserMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *MFSUserMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *MFSUserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *MFSUserMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *MFSUserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *MFSUserMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *MFSUserMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown MFSUser unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *MFSUserMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown MFSUser edge %s", name)
}
